names = []
names.append('jack')
names.append('rose')
names.append('vsman')
print(names)
ncome = names.pop(1)
print('but ' + ncome +' because some reason not come')
print(names)
print('beause i have big tables,can invite more guests')
names.insert(0,'justin')
print('invite justin')
names.insert(2,'nike')
print('invite nike')
names.append('pow')
print('invite pow')
print( names)
